name: "Build and Release"

on:
  push:
    branches: [ main ]
jobs:
  build-and-release:
    name: "Build and Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_dev"
          prerelease: true
          title: "Latest Developement Snapshot"
          files: "target/hibiscus-library-server-*.*.*.jar"
